### ISSUE TITLE
Will activate and shuffle but skipping has no effect. 

### ISSUE THREAD

**Issue by Dadstruction** [Dreistein/vlc_history_shuffle#2]
Thank you for making this. It's just what I've been looking for for years. Unfortunately, maybe VLC has changed the interface? 

Using VLC 3.0.11.1. 

When activated, I get the following messages. 

lua info: [HShuffle] starting
lua info: [HShuffle] using data file /Users/patagium/Library/Application Support/org.videolan.vlc/better_playlist_data.csv
lua debug: [HShuffle] initializing playlist
lua debug: [HShuffle] randomizing playlist

That's the last I get. The playing_changed function doesn't appear to be called whether files end normally or by skipping. It just plays through the shuffled playlist.

**Comment by Dadstruction** [comment]
Oh dear. IT looks like it's a VLC for OS X issue. 
https://trac.videolan.org/vlc/ticket/22778

Apparently playing_changed is never called.

**Comment by Dreistein** [comment]
Yes, while building the plugin, I found all sorts of strange behavior and lua builtins are not really documented. 

Closing for now, because it's an upstream issue.
